=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT videolibrary (nameSite,siteLink,videos,studios,actors)>
<!ELEMENT nameSite (#PCDATA)>
<!ELEMENT siteLink (#PCDATA)>

<!ELEMENT videos (video+)>
<!ELEMENT video (filmName,duration,country,year,plot,audioLanguage,rating,actorsIN)>
<!ELEMENT filmName (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT year (#PCDATA) >
<!ELEMENT plot (#PCDATA) >
<!ELEMENT audioLanguage (#PCDATA) >
<!ELEMENT rating (#PCDATA) >
<!ELEMENT actorsIN (actor-ref)>
<!ELEMENT actor-ref (#PCDATA)>
<!ATTLIST actor-ref
              actorID IDREF #REQUIRED >
<!ATTLIST video 
            isHd (yes|no) #REQUIRED
            hasSubtitle (yes|no) #REQUIRED
            gendre (action|adventure|comedy|romantic|drama) #REQUIRED
            produced-by IDREF #REQUIRED
            type (movie|tvShow) #REQUIRED>

<!ELEMENT studios (studio+)>
<!ELEMENT studio (studioName,director,address,phone)>
<!ATTLIST studio
              id ID #REQUIRED >
<!ELEMENT studioName (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA) >
<!ELEMENT actors (actor+)>
<!ELEMENT actor (name,countryActor,email,actorPhone,socialNetworkLink,nativeLanguage)>
<!ATTLIST actor
              gender (M|F) #REQUIRED
              age NMTOKEN #REQUIRED
              id ID #REQUIRED>
<!ELEMENT name (first,last)>
<!ELEMENT first (#PCDATA) >
<!ELEMENT  last (#PCDATA) >
<!ELEMENT countryActor (#PCDATA) >
<!ELEMENT  email (#PCDATA) >
<!ELEMENT  actorPhone (#PCDATA) >
<!ELEMENT  socialNetworkLink (#PCDATA) >
<!ELEMENT  nativeLanguage (#PCDATA) >

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
      <video isHd="no" hasSubtitle='yes' gendre='drama' produced-by='s23' type='tvShow'>
            <filmName>Семейство Фостър</filmName>
            <duration>60</duration>
            <country>САЩ</country>
            <year>2013</year>
            <plot>
              Семейство Фостър е драма за семейство със смесица от деца – осиновени и биологични,
              отгледани от две майки. Стеф Фостър е полицай, а партньорката и Лина Адамс е заместник
              директор в училище. Двете заедно имат едно сплотено семейство, заедно с сина на Стеф
              от предишен брак и техните осиновени близнаци Мариана и Хесус. Техният живот се променя
              по неочакван начин, когато Лина среща Кали, тийнейджър с агресивно минало, която е сменила
              няколко приемни семейства. Лина и Стеф я приемат в дома си като мислят, че ще бъде само за
              няколко седмици, докато и намерят постоянен дом.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>7</rating>
            <actorsIN>
                <actor-ref actorID='a39'/>  
            </actorsIN>
       </video>
      
    <video isHd='yes' hasSubtitle='yes' gendre='drama' produced-by='s24' type='tvShow'>
            <filmName>Малки сладки лъжкини</filmName>
            <duration>45</duration>
            <country>САЩ</country>
            <year>2010</year>
            <plot>
              Историята разказва за четирите гимназистки – Ария, Хана, Емили и Спенсър.
              В един прекрасен ден всяко от момичетата започва да получава заплашителни
              съобщения от някой с инициал „А“. Те започват да си мислят, че това е Алисън – тяхната
              „пчела майка“, суперпопулярното момиче на което всеки завижда и която знае всяка тяхна тайна.
              Но тя е изчезнала преди 1 година и скоро намират тялото ѝ, а ако не тя е мистериозния човек с
              под инициалът „А“, кой е тогава ? Така в привидно спокойния Роузууд, вече нищо не е сигурно,
              защото всички техни тайни от най – малките и невинни до най – големите и опасни, са заплашени 
              да излязат наяве. А това е само началото, защото малките сладурани ще си плащат скъпо за всичко.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a41'/> 
            </actorsIN>
       </video>


      <video isHd='no' hasSubtitle='yes' gendre='drama' produced-by='s48' type='tvShow'>
        <filmName>Как се запознах с майка ви</filmName>
        <duration>22</duration>
        <country>САЩ</country>
        <year>2005</year>
        <plot>
          През 2030 г. Тед Мозби (озвучен от Боб Сагет) събира дъщеря си и сина си да им разкаже историята
          за това, как се е запознал с майка им.
          Историята започва през 2005 г., когато Тед (Джош Раднор) е самотен, 27-годишен архитект, живеещ 
          с двамата си най-добри приятели от университета – Маршъл Ериксен (Джейсън Сийгъл), студент по
          право и приятелката му, с която се среща повече от 9 години – Лили Олдрин (Алисън Ханигън), 
          учителка в детска градина.
          Тяхната любов кара Тед да се замисли за сериозна връзка и да опитва да намери своята половинка,
          за огромно възмущение на приятеля им Барни Стинсън (Нийл Патрик Харис) – непоправим женкар с 
          доходна, макар и неизвестна корпоративна професия. Когато Тед започва да търси идеалното момиче,
          Барни измисля игра, с която да го представя на момичетата: „Здрасти, познаваш ли Тед?“.
          Така Тед се запознава с амбициозната млада репортерка Робин Шербатски (Коби Смолдърс), в която бързо
          се влюбва и тя става част от групата приятели.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>5</rating>
        <actorsIN>
          <actor-ref actorID='a42'/>
        </actorsIN>
      </video>
    </videos>


  <studios>
    <studio id='s23'>
      <studioName>Warner Bros. studios</studioName>
      <director>Брад Бредуик</director>
      <address>САЩ</address>
      <phone>4535</phone>
    </studio>
  
   <studio id='s24'>
      <studioName>ABC Family</studioName>
      <director>Сара Шепърд</director>
      <address>САЩ</address>
      <phone>4735</phone>
    </studio>

    <studio id='s48'>
      <studioName> 20th Century Fox</studioName>
      <director>Картър Бейс</director>
      <address>САЩ</address>
      <phone>9745</phone>
    </studio>
  </studios>
  
    <actors>
        <actor gender='F' age='22' id='a39'>
            <name>
                <first>Мая</first>
                <last>Мичъл</last>
            </name>
            <countryActor>Лизмор, Австралия</countryActor>
            <email>mitchell@gmail.com</email>
            <actorPhone>213698</actorPhone>
            <socialNetworkLink>http://www.imdb.com/name/nm2314596/?ref_=tt_cl_t5</socialNetworkLink>
            <nativeLanguage>английски език</nativeLanguage>
        </actor>

      <actor gender='F' age='26' id='a42'>
        <name>
          <first>Луси</first>
          <last>Хейл</last>
        </name>
        <countryActor>Тенеси, САЩ</countryActor>
        <email>Hale@gmail.com</email>
        <actorPhone>456972</actorPhone>
        <socialNetworkLink>https://twitter.com/_LucyHale_</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>
    
        <actor gender='F' age='20' id='a41'>
            <name>
                <first>Саша</first>
                <last>Питърс</last>
            </name>
            <countryActor>Йоханесбург,Южна Африка</countryActor>
            <email>Peters@gmail.com</email>
            <actorPhone>129874</actorPhone>
            <socialNetworkLink>https://twitter.com/SashaaPieterse</socialNetworkLink>
            <nativeLanguage>английски език</nativeLanguage>
        </actor>
    
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">-->
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="no" hasSubtitle='yes' gendre='comedy' produced-by='s4' type='movie'>
            <filmName>Сам вкъщи 1</filmName>
            <duration>103</duration>
            <country>САЩ</country>
            <year>1990</year>
            <plot>Кевин Маккалистър (Маколи Кълкин) е забравен сам у дома на Коледа, докато неговите родители
                отиват на ваканция със самолет. Той не се страхува, когато разбира, че е останал сам, но вечерта
                е посетен от двама крадци – Хари и Марв (Джо Пеши и Даниъл Стърн). Кевин им прави различни капани,
                за да им попречи. Родителите му осъзнават едва в самолета, че са оставили Кевин сам и майка му се
                качва на кола, щедро предложена от пътуващи музиканти, за да се върне обратно (тъй като по това време
                няма друг полет обратно). Накрая полицията залавя Хари и Марв. Майка му пристига първа, и само минути
                след това пристигат бащата и другите деца, които са хванали следващия полет.
            </plot>
          <audioLanguage>английски език</audioLanguage>
          <rating>9</rating>
            <actorsIN>
                <actor-ref actorID='a5'/>
            </actorsIN>
        </video>

        <video isHd='yes' hasSubtitle='yes' gendre='action' produced-by='s3' type='movie'>
            <filmName>Турнирът</filmName>
            <duration>95</duration>
            <country>Великобритания</country>
            <year>2009</year>
            <plot>На всеки 7 години, в някой произволен град се сформира "Турнирът". Кралска битка между 30 
                от най-смъртоносните бойци в света. Последният оцелял печели 10 милиона и титлата
                "Първи в света". Всички битки се заснемат и се излъчват на кодиран канал, където 
                милиардери залагат богатствата си. Играта започва, но дали фаворитите ще са подготвени за това, което ги очаква...
            </plot>
          <audioLanguage>английски език</audioLanguage>
          <rating>4</rating>
            <actorsIN>
                <actor-ref actorID='a6'/>
            </actorsIN>
        </video>


      <video isHd='yes' hasSubtitle='yes' gendre='adventure' produced-by='s34' type='movie'>
        <filmName>300</filmName>
        <duration>116</duration>
        <country>САЩ</country>
        <year>2006</year>
        <plot>
          Главния герой е цар Леонид, който през 480 г. пр. Хр. води война с персийкия цар Ксеркс. 
          Взел триста от най-добрите си мъже, той бива запомнен в историята с битката си.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>3</rating>
        <actorsIN>
          <actor-ref actorID='a4'/>
        </actorsIN>
      </video>
    </videos>
    
    
    <studios>
        <studio id='s4'>
            <studioName>Bonanza Productionss</studioName>
            <director>Кевин Уилямсън</director>
            <address>САЩ</address>
            <phone>752513</phone>
        </studio>  
        
        <studio id='s3'>
            <studioName>AV Pictures</studioName>
            <director>Скот Ман</director>
            <address>Манчестър, Великобритания</address>
            <phone>654542</phone>
        </studio>

      <studio id='s34'>
        <studioName>Warner Bros</studioName>
        <director>Зак Снайдър</director>
        <address>Грийн Бей, САЩ</address>
        <phone>786531</phone>
      </studio>
      
    </studios>
  
  <actors>
    <actor gender='F' age='42' id='a4'>
      <name>
        <first>Лина</first>
        <last>Хийди</last>
      </name>
      <countryActor>Бермудски острови</countryActor>
      <email>Headey@gmail.com</email>
      <actorPhone>244530</actorPhone>
      <socialNetworkLink>https://twitter.com/IAMLenaHeadey</socialNetworkLink>
      <nativeLanguage>английски език</nativeLanguage>
    </actor>
    
  <actor gender='M' age='35' id='a5'>
    <name>
      <first>Маколи</first>
      <last>Кълкин</last>
    </name>
    <countryActor>САЩ</countryActor>
    <email>Culkin@gmail.com</email>
    <actorPhone>224551</actorPhone>
    <socialNetworkLink>https://twitter.com/macaulaycarsonc</socialNetworkLink>
    <nativeLanguage>английски език</nativeLanguage>
  </actor>

  <actor gender='M' age='37' id='a6'>
            <name>
                <first>Иън</first>
                <last>Сомърхолдър</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Somerholder@gmail.com</email>
    <actorPhone>114531</actorPhone>
    <socialNetworkLink>https://twitter.com/iansomerhalder</socialNetworkLink>
    <nativeLanguage>английски език</nativeLanguage>
        </actor>
        
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="yes" hasSubtitle='yes' gendre='action' produced-by='s8' type='movie'>
            <filmName>Туристът</filmName>
            <duration>103</duration>
            <country>Франция</country>
            <year>2010</year>
            <plot>Франк (Джони Деп) е американски турист, който посещава Италия, за да забрави жената,
                която го изоставя след една голяма любов. Във влака за Венеция с него се запознава
                красивата Елиз (Анджелина Джоли), която го привлича. Франк се отдава на увлечението,
                но в един момент разбира, че всеки контакт с тайнствената дама е опасен за живота му.
            </plot>
          <audioLanguage>английски език</audioLanguage>
          <rating>5</rating>
            <actorsIN>
                <actor-ref actorID='a10'/>
            </actorsIN>
        </video>
        
        
        <video isHd='yes' hasSubtitle='yes' gendre='adventure' produced-by='s7' type='movie'>
            <filmName>Лара Крофт.Томб Рейдър</filmName>
            <duration>101</duration>
            <country>САЩ</country>
            <year>2001</year>
            <plot>Във филма „Лара Крофт: Томб Рейдър“ („Lara Croft: Tomb Raider“) член на богато аристократично
                семейство, Лара Крофт е „Томб Рейдър”. Тя колекционира древни артефакти от руините на храмове 
                и градове по целия свят и няма нищо против да се подлага на смъртоносни опасности, за да се сдобие с тях.
                Планетите от слънчевата система се събират в планетарно изравняване, което се случва на всеки 5000 години,
                а тайно общество, наречено илюминати, търси талисман, който дава на притежателя си способността да
                контролира времето. В „Лара Крофт: Томб Рейдър“ („Lara Croft: Tomb Raider“) илюминатите се нуждаят от
                часовник-ключ, който да им помогне в издирването, но се налага да намерят талисмана веднага или да чакат до
                следващото планетарно изравняване.Лара случайно открива този ключ, а те го задигат. Като научава за скритите
                им цели, единственото, което й остава, е да вземе ключа, да открие и унищожи талисмана, преди илюминатите
                да се доберат до него.
            </plot>
          <audioLanguage>английски език</audioLanguage>
          <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a10'/>
            </actorsIN>
        </video>
        
        
        
        <video isHd='no' hasSubtitle='yes' gendre='action' produced-by='s9' type='movie'>
            <filmName>Мистър и мисис Смит</filmName>
            <duration>120</duration>
            <country>САЩ</country>
            <year>2005</year>
            <plot>Екшън, в който Джон и Джейн Смит са обикновена семейна двойка с обикновен, поизносен брак. Но всеки от тях
                крие пикантна тайна - всъщност и двамата са легендарни наемни убийци, работещи за конкурентни компании. Когато
                шокиращата истина излиза наяве, Джон и Джейн се изправят един срещу друг. Двамата най-опитни убийци на света
                осъзнават, че живеят под един покрив.
            </plot>
          <audioLanguage>английски език</audioLanguage>
          <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a10'/>
            </actorsIN>
        </video>
        
    </videos>
    
    
    <studios>
        <studio id='s7'>
            <studioName>GK Films</studioName>
            <director>Флориан Хенкел фон Донерсмарк</director>
            <address>Германия</address>
            <phone>684512</phone>
        </studio> 
        
        <studio id='s8'>
            <studioName>Paramount Pictures</studioName>
            <director>Саймън Уест</director>
            <address>Великобритания</address>
            <phone>654544</phone>
        </studio>  
        
        <studio id='s9'>
            <studioName>20th Century Fox</studioName>
            <director>Дъг Лайман</director>
            <address>САЩ</address>
            <phone>153542</phone>
        </studio> 
    </studios>
    
    <actors>
        <actor gender='F' age='40' id='a10'>
            <name>
                <first>Анджелина</first>
                <last>Джоли</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Jolie@gmail.com</email>
          <actorPhone>111531</actorPhone>
          <socialNetworkLink>https://twitter.com/AngeelinaJolie</socialNetworkLink>
          <nativeLanguage>английски език</nativeLanguage>
        </actor>

    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="no" hasSubtitle='no' gendre='action' produced-by='s14' type='tvShow'>
            <filmName>Под прикритие</filmName>
            <duration>52</duration>
            <country>България</country>
            <year>2011</year>
            <plot>
              Под прикритие“ е реалистичен и модерен поглед към престъпния свят в България.
              Сериалът разкрива в детайли психологията на престъплението и показва истинския
              живот в мафията и в полицията.
              Специално обученият агент Мартин (Ивайло Захариев) получава най-опасната мисия
              в България – да се внедри в редиците на мафиотския бос – Петър Туджаров – Джаро
              (Михаил Билалов). По пътя към целта Мартин трябва да премине през много изпитания
              и да се слее с престъпния свят. Задачата му се усложнява още повече, когато среща
              момичето на шефа – Съни (Ирена Милянкова). Докато действа под прикритие и се издига
              в йерархията на мафиотите, Мартин попада в свят на насилие корупция и престъпления
            </plot>
            <audioLanguage>български език</audioLanguage>
            <rating>4</rating>
            <actorsIN>
                <actor-ref actorID='a21'/>  
            </actorsIN>
       </video>



      <video isHd='no' hasSubtitle='no' gendre='action' produced-by='s15' type='movie'>
        <filmName>Love.net</filmName>
        <duration>109</duration>
        <country>България</country>
        <year>2011</year>
        <plot>
          Филмът проследява паралелно историите на галерия от персонажи, опитващи
          се да коригират живота си чрез Интернет или просто да се забавляват в
          мрежата, както и на няколко двойки, свързали живота си чрез сайтовете 
          за запознанства. LOVЕ.NET разказва за любовта във всичките ѝ проявления
          – за неизбежната и необяснима любов, но и за повърхностната, бързо
          ликвидна любов.
        </plot>
        <audioLanguage>български език</audioLanguage>
        <rating>4</rating>
        <actorsIN>
          <actor-ref actorID='a20'/>
        </actorsIN>
      </video>


      <video isHd='no' hasSubtitle='no' gendre='action' produced-by='s40' type='movie'>
        <filmName>Лов на дребни хищници</filmName>
        <duration>95</duration>
        <country>България</country>
        <year>2010</year>
        <plot>
          Михаил има трудности в общуването си с хората, преди да срещне любовта и да се
          запознае с Хани, Бети и Спейса. Четиримата младежи наивно решават да изкарат лесни
          пари. Те не подозират, че един непознат с тъмно минало и проблемно настояще ще 
          преобърне живота им.
        </plot>
        <audioLanguage>български език</audioLanguage>
        <rating>5</rating>
        <actorsIN>
          <actor-ref actorID='a22'/>
        </actorsIN>
      </video>
    </videos>
    
    
    <studios>
        <studio id='s14'>
            <studioName>Fox</studioName>
            <director>Иван Дойков</director>
            <address>София, България</address>
            <phone>121212</phone>
        </studio>


      <studio id='s15'>
        <studioName>Мирамар филм</studioName>
        <director>Илиян Джевелеков</director>
        <address>София, България</address>
        <phone>868584</phone>
      </studio>

      <studio id='s40'>
        <studioName>Мирамар филм</studioName>
        <director>Цветодар Марков</director>
        <address>София, България</address>
        <phone>123123</phone>
      </studio>
    </studios>
    
    <actors>
        <actor gender='M' age='35' id='a20'>
            <name>
                <first>Захари</first>
                <last>Бахаров</last>
            </name>
            <countryActor>България</countryActor>
            <email>zaharybaharov@gmail.com</email>
            <actorPhone>111111</actorPhone>
            <socialNetworkLink>http://www.imdb.com/name/nm1707712/</socialNetworkLink>
            <nativeLanguage>български език</nativeLanguage>
        </actor>
        
        
        <actor gender='M' age='31' id='a22'>
            <name>
                <first>Ивайло</first>
                <last>Захариев</last>
            </name>
            <countryActor>България</countryActor>
            <email>ivaylozahariev@gmail.com</email>
            <actorPhone>114532</actorPhone>
            <socialNetworkLink>https://www.facebook.com/FansIvayloZahariev</socialNetworkLink>
            <nativeLanguage>български език</nativeLanguage>
        </actor>


      <actor gender='F' age='30' id='a21'>
        <name>
          <first>Ирена</first>
          <last>Милянкова</last>
        </name>
        <countryActor>България</countryActor>
        <email>milyankova@gmail.com</email>
        <actorPhone>333333</actorPhone>
        <socialNetworkLink>-</socialNetworkLink>
        <nativeLanguage>български език</nativeLanguage>
      </actor>
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary10.xml
<?xml version="1.0" encoding="utf-8"?>
<!--<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">-->
<videolibrary>
  <nameSite>Арена София</nameSite>
  <siteLink>www.arenaSofia.bg</siteLink>
  <videos>
    
    <video isHd="no" hasSubtitle='yes' gendre='drama' produced-by='s17' type='tvShow'>
      <filmName>Дневниците на вампира</filmName>
      <duration>45</duration>
      <country>САЩ</country>
      <year>2009</year>
      <plot>
        Сериалът се заснема в Мистик Фолс в щата Вирджиния, малък град, преследван и заобиколен от
        свръхестествени същества. Поредицата проследява живота на Елена Гилбърт (Нина Добрев), която се
        влюбва във вампира Стефан Салваторе (Пол Уесли), а скоро се оказва уловена в любовен триъгълник
        между Стефан и неговия по-голям брат, Деймън (Иън Сомърхолдър), които едновременно са преследвани
        и от миналото, което са имали с Катрин Пиърс/Катерина Петрова. Сериалът също така се фокусира върху
        живота на приятелите на Елена и другите жители на Мистик Фолс. Появява се и нов главен герой, който
        е един от "първородните" вампири – Клаус
      </plot>
      <audioLanguage>английски език</audioLanguage>
      <rating>7</rating>
      <actorsIN>
        <actor-ref actorID='a25'/>
      </actorsIN>
    </video>


    <video isHd="no" hasSubtitle='no' gendre='drama' produced-by='s42' type='tvShow'>
      <filmName>Отплата</filmName>
      <duration>60</duration>
      <country>България</country>
      <year>2012</year>
      <plot>
        Един мъж е несправедливо обвинен и осъден да лежи в затвора за престъпление, което не е извършил.
        Той се казва Ангел и събира банда отмъстители. Изглежда щастлив семеен мъж. Има красива съпруга
        и 5-годишна дъщеря. При катастрофа обаче Ангел ги губи и двете. Заради тази катастрофа той е потрошен
        и е между живота и смъртта. Изпада в кома за кратко.
      </plot>
      <audioLanguage>български език</audioLanguage>
      <rating>4</rating>
      <actorsIN>
        <actor-ref actorID='a29'/>
      </actorsIN>
    </video>


    <video isHd="no" hasSubtitle='yes' gendre='action' produced-by='s44' type='movie'>
      <filmName>Бандитки</filmName>
      <duration>93</duration>
      <country>Франция</country>
      <year>2006</year>
      <plot>
        Мексико, 1848 г. Сара е богата и образована в Европа, дъщеря на собственика на единствената банка
        в града. Мария е грубовата селянка. Бащите им са убити в един и същ ден. Съдбата ги среща и те
        стават приятелки и съдружнички в обирането на банки. Опитният държавен криминалист Куентин е
        извикан да ги залови, но в името на правдата по-късно той се присъединява към тях...
      </plot>
      <audioLanguage>английски език</audioLanguage>
      <rating>5</rating>
      <actorsIN>
        <actor-ref actorID='a33'/>
      </actorsIN>
    </video>
  </videos>

  <studios>
    <studio id='s17'>
      <studioName>Bonanza Productionss</studioName>
      <director>Кевин Уилямсън</director>
      <address>САЩ</address>
      <phone>752513</phone>
    </studio>

    <studio id='s42'>
      <studioName>Нова телевизия</studioName>
      <director>Иво Симеонов</director>
      <address>България</address>
      <phone>666444</phone>
    </studio>

    <studio id='s44'>
      <studioName>20th Century Fox</studioName>
      <director>Люк Бесон</director>
      <address>Париж, Франция</address>
      <phone>632598</phone>
    </studio>
  </studios>

  <actors>
    <actor gender='M' age='33' id='a25'>
      <name>
        <first>Пол</first>
        <last>Уесли</last>
      </name>
      <countryActor>САЩ</countryActor>
      <email>Wesley@gmail.com</email>
      <actorPhone>984531</actorPhone>
      <socialNetworkLink>https://twitter.com/paulwesley</socialNetworkLink>
      <nativeLanguage>
        английски език
      </nativeLanguage>
    </actor>

    <actor gender='M' age='37' id='a29'>
      <name>
        <first>Орлин</first>
        <last>Павлов</last>
      </name>
      <countryActor>София,България</countryActor>
      <email>OrlinPavlov@gmail.com</email>
      <actorPhone>456213</actorPhone>
      <socialNetworkLink>https://www.facebook.com/orlinopavlov</socialNetworkLink>
      <nativeLanguage>български език</nativeLanguage>
    </actor>


    <actor gender='F' age='42' id='a33'>
      <name>
        <first>Пенелопе</first>
        <last>Крус</last>
      </name>
      <countryActor>Мадрид, Испания</countryActor>
      <email>PeneloppeKruz@gmail.com</email>
      <actorPhone>123695789</actorPhone>
      <socialNetworkLink>https://twitter.com/penelopecruz1</socialNetworkLink>
      <nativeLanguage>испански език</nativeLanguage>
    </actor>
  </actors>
</videolibrary>
