=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT videolibrary (nameSite,siteLink,videos,studios,actors)>
<!ELEMENT nameSite (#PCDATA)>
<!ELEMENT siteLink (#PCDATA)>

<!ELEMENT videos (video+)>
<!ELEMENT video (filmName,duration,country,year,plot,audioLanguage,rating,actorsIN)>
<!ELEMENT filmName (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT year (#PCDATA) >
<!ELEMENT plot (#PCDATA) >
<!ELEMENT audioLanguage (#PCDATA) >
<!ELEMENT rating (#PCDATA) >
<!ELEMENT actorsIN (actor-ref)>
<!ELEMENT actor-ref (#PCDATA)>
<!ATTLIST actor-ref
              actorID IDREF #REQUIRED >
<!ATTLIST video 
            isHd (yes|no) #REQUIRED
            hasSubtitle (yes|no) #REQUIRED
            gendre (action|adventure|comedy|romantic|drama) #REQUIRED
            produced-by IDREF #REQUIRED
            type (movie|tvShow) #REQUIRED>

<!ELEMENT studios (studio+)>
<!ELEMENT studio (studioName,director,address,phone)>
<!ATTLIST studio
              id ID #REQUIRED >
<!ELEMENT studioName (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA) >
<!ELEMENT actors (actor+)>
<!ELEMENT actor (name,countryActor,email,actorPhone,socialNetworkLink,nativeLanguage)>
<!ATTLIST actor
              gender (M|F) #REQUIRED
              age NMTOKEN #REQUIRED
              id ID #REQUIRED>
<!ELEMENT name (first,last)>
<!ELEMENT first (#PCDATA) >
<!ELEMENT  last (#PCDATA) >
<!ELEMENT countryActor (#PCDATA) >
<!ELEMENT  email (#PCDATA) >
<!ELEMENT  actorPhone (#PCDATA) >
<!ELEMENT  socialNetworkLink (#PCDATA) >
<!ELEMENT  nativeLanguage (#PCDATA) >

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary1.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!--<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">-->
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd='yes' hasSubtitle='yes' gendre='action' produced-by='s2' type='movie'>
            <filmName>Седмият син</filmName>
            <duration>103</duration>
            <country>САЩ</country>
            <year>2014</year>
            <plot>В ера на вълшебства, когато легенди и магия се сблъскват,
                единственият останал воин от мистичен орден (носителят на „Оскар“ Джеф Бриджис) 
                пътува по цялата земя, за да открие герой, който според предсказанията ще се роди
                с невероятни сили – последният Седми син (Бен Барнс).Изтръгнат от спокойния си
                живот на рибар, неподозираният млад герой се впуска в дръзко приключение заедно със
                своя закоравял в битките ментор, за да срази кралица на мрака (Джулиан Мур) и нейната
                армия от свръхестествени убийци, които тя е пратила срещу кралството им.Режисьор на
                СЕДМИЯТ СИН е Сергей Бодром по сценарий на Чарлс Лийвит и Стив Найт и екранен сюжет на
                Мат Грийнбърг, по поредицата романи „Хрониките Уордстоун“ на Джоузеф Дилейни. 
                Продуценти на филма са Бейзъл Иванюк, Томас Тъл и Лайънъл Уиграм. Изпълнителни продуценти
                са Джон Яшни, Брент О’Конър и Алисия Котър със съпродуценти Джилиан Шеър и Ерика Лий. 
                По поредицата романи „Хрониките Уордстоун“ от Джоузеф Дилейни .
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>5</rating>
            <actorsIN>
                <actor-ref actorID='a1'/>
            </actorsIN>
       </video>
        
        
        <video isHd='no' hasSubtitle='yes' gendre='adventure' produced-by='s1' type='tvShow'>
            <filmName>Игра на тронове</filmName>
            <duration>45</duration>
            <country>САЩ</country>
            <year>2011</year>
            <plot>С шеметния си бяг от скована в жесток студ страна към земи на вечно лято и охолно безгрижие,
                ИГРА НА ТРОНОВЕ е сказание за владетели и владетелки, воини и чародеи, наемни убийци и незаконородени
                претенденти за власт, появили се във времена на мрачни поличби. Тук странна войнствена орда се сражава
                с мечове, изковани от невиждан от човека метал, жестоко дивашко племе сее безумие сред хората, свиреп
                млад принц от кръвта на дракона разменя сестра си, за да си върне трона, едно дете се губи в сумрака
                между живота и смъртта и една решена на всичко жена предприема опасно пътуване, за да защити това, което
                й е скъпо. Сред заговори и коварства, трагедии и вероломство, победи и насилия, съюзници и врагове, съдбата
                на Старките виси на косъм и всяка от страните се бори за победа в най-смъртоносния конфликт: Играта на тронове.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>3</rating>
            <actorsIN>
                <actor-ref actorID='a2'/>
            </actorsIN>
        </video>
        
    
       <video isHd='no' hasSubtitle='yes' gendre='comedy' produced-by='s33' type='movie'>
            <filmName>Големият Лебовски</filmName>
            <duration>117</duration>
            <country>САЩ</country>
            <year>1998</year>
            <plot>Големият Лебовски“ (на английски: The Big Lebowski) е американско-британски криминален комедиен филм от 1998
            година на режисьорите братя Коен по техен собствен сценарий.
            В центъра на сюжета е лосанджелиски безделник, който е ангажиран от свой съименник милионер да предаде откупа за 
            отвлечената му съпруга, но попада в поредица от премеждия. Главните роли се изпълняват от Джеф Бриджис, 
            Джон Гудман, Стив Бушеми.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>4</rating>
            <actorsIN>
                <actor-ref actorID='a3'/>
            </actorsIN>
        </video>
    </videos>
    
    
    <studios>
        <studio id='s1'>
            <studioName>HBO</studioName>
            <director>Дейвид Бениоф</director>
            <address>Ню Йорк, САЩ</address>
            <phone>654512</phone>
        </studio> 
        
        <studio id='s2'>
            <studioName>Titanic Studios</studioName>
            <director>Сергей Бодров</director>
            <address>Москва,Русия</address>
            <phone>654513</phone>
        </studio>  
  
      <studio id='s33'>
            <studioName>Polygram Filmed Entertainment</studioName>
            <director>Братя Коен</director>
            <address>Минесота, САЩ</address>
            <phone>456925</phone>
        </studio>  
    </studios>
    
    <actors>
        <actor gender='M' age='66' id='a1'>
            <name>
                <first>Джеф</first>
                <last>Бриджис</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Bridges@gmail.com</email>
            <actorPhone>224531</actorPhone>
            <socialNetworkLink>https://twitter.com/TheJeffBridges</socialNetworkLink>
            <nativeLanguage>английски език</nativeLanguage>
        </actor>
        
        
        <actor gender='M' age='45' id='a2'>
            <name>
                <first>Николай </first>
                <last>Костер-Валдау</last>
            </name>
            <countryActor>Дания</countryActor>
            <email>Waldau@gmail.com</email>
            <actorPhone>224532</actorPhone>
            <socialNetworkLink>https://twitter.com/NikolajCWaldau</socialNetworkLink>
            <nativeLanguage>датски език</nativeLanguage>
        </actor>
    

        <actor gender='F' age='55' id='a3'>
         <name>
               <first>Джулиан</first>
               <last>Мур</last>
        </name>
        <countryActor>САЩ</countryActor>
        <email>Moore@gmail.com</email>
        <actorPhone>224530</actorPhone>
        <socialNetworkLink>https://twitter.com/_juliannemoore</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
        </actor>
    
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary7.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
  <nameSite>Арена София</nameSite>
  <siteLink>www.arenaSofia.bg</siteLink>
  <videos>
    
    
<video isHd="yes" hasSubtitle='yes' gendre='action' produced-by='s13' type='movie'>
  <filmName>Дивергенти</filmName>
  <duration>139</duration>
  <country>САЩ</country>
  <year>2014</year>
  <plot>
    „Дивергенти“ е вълнуващо екшън приключение в един свят, в който хората са разделени на различни
    фракции въз основа на човешките добродетели. Трис Прайър (Шайлийн Уудли) е предупредена, че е различна
    (дивергентна) и никога няма да може да стане част от някоя от групите. Когато разкрива, че един от
    фракционните лидери (Кейт Уинслет) крои заговор за унищожението на всички дивергенти, Трис е принудена да
    започне да се доверява на тайнствен мъж на име Фор (Тио Джеймс), с когото трябва да стигне до отговора на
    един жизненоважен въпрос, преди да е станало твърде късно: Какво прави дивергентите толкова опасни?
  </plot>
  <audioLanguage>английски език</audioLanguage>
  <rating>7</rating>
  <actorsIN>
    <actor-ref actorID='a17'/>
  </actorsIN>
</video>

    
 <video isHd="no" hasSubtitle='yes' gendre='action' produced-by='s38' type='movie'>
  <filmName>Лондонски поля</filmName>
  <duration>139</duration>
  <country>САЩ</country>
  <year>2015</year>
  <plot>
    Саймън Янг изкарва препитанието си като писател. За огромно негово нещастие, той попада
    в групата на тези автори, които не могат да напишат нищо смислено от дълго време насам.
    Изминали са вече три десетилетия, през които Саймън така и не успява да продаде нищо на книжния
    пазар. Но дали скоро той ще получи шанса да се превърне в един от най - продаваните писатели?
  </plot>
  <audioLanguage>английски език</audioLanguage>
  <rating>3</rating>
  <actorsIN>
    <actor-ref actorID='a18'/>
  </actorsIN>
</video>

    <video isHd="yes" hasSubtitle='yes' gendre='drama' produced-by='s39' type='movie'>
      <filmName>Стив Джобс</filmName>
      <duration>122</duration>
      <country>САЩ</country>
      <year>2015</year>
      <plot>
        Филмът се концентира върху взаимоотношенията на Стив Джобс (Майкъл Фасбендер) с неговите приятели,
        близки и колеги. Тези взаимоотношения са представени чрез разговори между тях преди появата на
        Стив Джобс пред публика с цел представяне на нови технологични продукти. Основният акцент е поставен
        върху взаимоотношенията баща - дъщеря, като Джобс първоначално отрича да е биологичен баща на дъщеря
        си, а впоследствие е упрекван от колеги и близки, че не е добър родител. Обръща се внимание и на
        споровете му със Стив Возняк (Сет Рогън), както и с бившия изпълнителен директор на Apple - Джон
        Скъли (Джеф Даниелс).
      </plot>
      <audioLanguage>английски език</audioLanguage>
      <rating>7</rating>
      <actorsIN>
        <actor-ref actorID='a19'/>
      </actorsIN>
    </video>
</videos>

  <studios>
  <studio id='s13'>
    <studioName>Summit Entertainment</studioName>
    <director>Нийл Бъргър</director>
    <address>САЩ</address>
    <phone>953542</phone>
  </studio>

    <studio id='s38'>
      <studioName>Muse Productions</studioName>
      <director>Матю Кълън</director>
      <address>САЩ</address>
      <phone>414141</phone>
    </studio>
    
    <studio id='s39'>
      <studioName>Legendary Pictures</studioName>
      <director>Дани Бойл</director>
      <address>Манчестър, Англия</address>
      <phone>555333</phone>
    </studio>
  </studios>


  <actors>
  <actor gender='F' age='24' id='a17'>
    <name>
      <first>Шейлийн</first>
      <last> Удли</last>
    </name>
    <countryActor>Калифорния, САЩ</countryActor>
    <email>Woodley@gmail.com</email>
    <actorPhone>724531</actorPhone>
    <socialNetworkLink>https://twitter.com/shailenewoodley?lang=bg</socialNetworkLink>
    <nativeLanguage>английски език</nativeLanguage>
  </actor>


    <actor gender='M' age='31' id='a18'>
      <name>
        <first>Тео</first>
        <last>Джеймс</last>
      </name>
      <countryActor>Оксфорд,Великобритания</countryActor>
      <email>James@gmail.com</email>
      <actorPhone>824531</actorPhone>
      <socialNetworkLink>https://twitter.com/theojamesff</socialNetworkLink>
      <nativeLanguage>английски език</nativeLanguage>
    </actor>

    <actor gender='F' age='40' id='a19'>
      <name>
        <first>Кейт</first>
        <last>Уинслет</last>
      </name>
      <countryActor>Рединг, Великобритания</countryActor>
      <email>Winslett@gmail.com</email>
      <actorPhone>784531</actorPhone>
      <socialNetworkLink>https://twitter.com/KateWinslet</socialNetworkLink>
      <nativeLanguage>английски език</nativeLanguage>
    </actor>
  </actors>
  </videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary19.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
      <video isHd="yes" hasSubtitle='yes' gendre='action' produced-by='s29' type='tvShow'>
        <filmName>От местопрестъплението: Маями</filmName>
        <duration>42</duration>
        <country>САЩ</country>
        <year>2012</year>
        <plot>
          „От местопрестъплението: Маями“ (на английски: CSI: Miami) е разклонение на известния
          американски сериал на CBS - „От местопрестъплението“. Също като първия сериал „От
          местопрестъплението: Маями“ се върти около група криминалисти. Неговото действие се
          развива в Маями, Флорида.
          Екипът разследва заплетени и необичайни убийства, опитвайки се да разкрие кой е убиецът
          и как е извършено престъплението. За разлика от другите два сродни сериала (съответно
          „От местопрестъплението“ и „От местопрестъплението: Ню Йорк“) тук се разследва по
          едно престъпление на епизод.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>6</rating>
        <actorsIN>
          <actor-ref actorID='a50'/>
        </actorsIN>
      </video>
        
      <video isHd='no' hasSubtitle='yes' gendre='drama' produced-by='s30' type='tvShow'>
            <filmName>Д-р Хаус</filmName>
            <duration>44</duration>
            <country>САЩ</country>
            <year>2004</year>
            <plot>
             Хаус често влиза в противоречие със своите колеги лекари, включително и със собствения
             си екип, тъй като много от хипотезите му за болестите на пациентите са базирани на прозрения,
             появяващи се от нищото, а понякога и спорни заключения. Пренебрежението му към болничните 
             правила и процедури често го вкарва в конфликт с шефката му, която е болничен администратор
             и декан на медицинския факултет, д-р Лиса Къди (Лиса Едълстийн). Единственият истински приятел
             на Хаус е д-р Джеймс Уилсън (Робърт Шон Ленард), началник на Отделението по онкология. 
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a52'/>
            </actorsIN>
       </video>
        
      
      <video isHd='no' hasSubtitle='yes' gendre='drama' produced-by='s52' type='movie'>
        <filmName>Престиж </filmName>
        <duration>130</duration>
        <country>САЩ</country>
        <year>2006</year>
        <plot>
          Престиж“ (на английски: The Prestige) е трилър-мистерия от 2006 г. на режисьора Кристофър Нолан, базиран на
          едноименния роман на Кристофър Прийст от 1995 г. Историята следва съперничеството между Робърт Анжие – Великия 
          Дантон (Хю Джакман) и Алфред Бордън – (Крисчън Бейл), конкурентни лондонски илюзионисти от края на 19 век.
          Погълнати от идеята да създадат най-изкусната илюзия, те се впускат в напрегната надпревара с трагични 
          последствия. Във филма участват още Майкъл Кейн, Скарлет Йохансон, Ребека Хол, Анди Съркис, Пайпър Перабо 
          и Дейвид Боуи в ролята на изобретателя Никола Тесла. Епистоларният роман на Прийст е адаптиран от Нолан и
          брат му, Джонатан Нолан, в типичната за Нолан нелинейна структура на повествованието. Сред изследваните
          мотиви са двуличност, обсебеност, саможертва и потайност. Филмът излиза на 20 октомври 2006 г., като получава
          добри отзиви от публиката и критиката, успешно представяне в боксофиса и две номинации за Оскар за Най-добро
          операторско майсторство и Най-добра художествена режисура.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>6</rating>
        <actorsIN>
          <actor-ref actorID='a57'/>
        </actorsIN>
      </video>
    </videos>


  <studios>
    <studio id='s29'>
      <studioName>Alliance Atlantis Communications</studioName>
      <director>Джери Брукхаймър</director>
      <address>САЩ</address>
      <phone>874562</phone>
    </studio>
  
   <studio id='s30'>
      <studioName>Heel and Toe Films</studioName>
      <director>Дейвид Шор</director>
      <address>САЩ</address>
      <phone>989898</phone>
    </studio>
    
    <studio id='s52'>
      <studioName>Touchstone Pictures</studioName>
      <director>Кристофър Нолан</director>
      <address>Лондон, Великобритания</address>
        <phone>3212</phone>
    </studio>
  </studios>
  
    <actors>
        <actor gender='M' age='60' id='a50'>
            <name>
                <first>Дейвид</first>
                <last>Карузо</last>
            </name>
            <countryActor>Бедфорд, САЩ</countryActor>
            <email>Caruso@gmail.com</email>
            <actorPhone>456231</actorPhone>
            <socialNetworkLink>https://twitter.com/davidcaruso1?lang=bg</socialNetworkLink>
            <nativeLanguage>английски език</nativeLanguage>
        </actor>
        
     <actor gender='M' age='56' id='a52'>
            <name>
                <first>Хю</first>
                <last>Лори</last>
            </name>
            <countryActor>Оксфорд, Великобритания</countryActor>
            <email>Laurie@gmail.com</email>
          <actorPhone>239745</actorPhone>
          <socialNetworkLink>https://twitter.com/hughlaurie?lang=bg</socialNetworkLink>
          <nativeLanguage>английски език</nativeLanguage>
        </actor>
    
       <actor gender='F' age='31' id='a57'>
        <name>
          <first>Скарлет</first>
          <last>Йохансон</last>
        </name>
        <countryActor>Ню Йорк, САЩ</countryActor>
        <email>Johansson@gmail.com</email>
        <actorPhone>111442</actorPhone>
        <socialNetworkLink>http://www.imdb.com/name/nm0424060/?ref_=tt_cl_t6</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="yes" hasSubtitle='yes' gendre='adventure' produced-by='s26' type='movie'>
            <filmName>Алиса в Страната на чудесата</filmName>
            <duration>108</duration>
            <country>САЩ</country>
            <year>2010</year>
            <plot>
              „Алиса в Страната на чудесата“ (на английски: Alice in Wonderland) е фентъзи филм
              от 2010, режисиран от Тим Бъртън. Адаптация по романите на Луис Карол Алиса в 
              страната на чудесата и Алиса в Огледалния свят, филмът използва техника, комбинираща
              живата игра с motion capture технология и stop motion анимация. Миа Вашиковска играе
              ролята на Алиса, заедно с Джони Деп като Лудият шапкар, Хелена Бонъм Картър като
              Червената кралица и Ан Хатауей в ролята на Бялата кралица.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a46'/> 
            </actorsIN>
       </video>
        
    
   <video isHd='yes' hasSubtitle='yes' gendre='adventure' produced-by='s26' type='movie'>
            <filmName>Алиса в огледалния свят</filmName>
            <duration>113</duration>
            <country>САЩ</country>
            <year>2016</year>
            <plot>
            „Алиса в Огледалния свят“ (на английски: Alice Through The Looking Glass) е предстоящ
            филм по книгата на Луис Карол. Жанрът е определен като приключенско фентъзи, а режисьор
            е Джеймс Бобин. Филмът е продуциран от Тим Бъртън, който е работил и по първата част. 
            Очаква се разпространението на филма да започне от 27 май 2016 г.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a46'/>
            </actorsIN>
       </video>

      <video isHd='no' hasSubtitle='yes' gendre='comedy' produced-by='s51' type='tvShow'>
        <filmName>Грозната Бети</filmName>
        <duration>45</duration>
        <country>САЩ</country>
        <year>2006</year>
        <plot>
          Бети живее с баща си Игнасио, който е нелегален имигрант, със своята сестра Хилда и племенника 
          си – Джъстин. Бащата на Даниъл – Брадфорд Мийд, е собственик на „Мийд Пъбликейшънс“, част от
          което е списанието „Моуд“. Съпругата на Брадфорд – Клеър Мийд, собственичка на „Моуд“, е алкохоличка,
          а брат му Алекс, който е в неизвестност от две години се завръща като Алексис, сменил пола си.
          Естествено и Даниъл се вписва в обстановката. Всички в „Моуд“ знаят, че всеки ден той дели леглото
          си с различна жена, а освен това има и проблем с наркотиците.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>5</rating>
        <actorsIN>
          <actor-ref actorID='a51'/>
        </actorsIN>
      </video>
    </videos>


  <studios>
    <studio id='s26'>
      <studioName>Уолт Дисни</studioName>
      <director>Тим Бъртън</director>
      <address>САЩ</address>
      <phone>98741</phone>
    </studio>

    <studio id='s51'>
      <studioName>Silent H Productions</studioName>
      <director>Фернандо Гаетан</director>
      <address>Колумбия</address>
      <phone>633215</phone>
    </studio>
  </studios>
  
    <actors>
        <actor gender='F' age='26' id='a46'>
            <name>
                <first>Миа</first>
                <last>Вашиковска</last>
            </name>
            <countryActor>Канбера, Австралия</countryActor>
            <email>Wasikowska@gmail.com</email>
            <actorPhone>654135</actorPhone>
            <socialNetworkLink>http://www.imdb.com/name/nm1985859/</socialNetworkLink>
            <nativeLanguage>английски език</nativeLanguage>
        </actor>

      <actor gender='M' age='41' id='a51'>
        <name>
          <first>Адам</first>
          <last>Родригес</last>
        </name>
        <countryActor>Ню Йорк, САЩ</countryActor>
        <email>Rodríguez@gmail.com</email>
        <actorPhone>974511</actorPhone>
        <socialNetworkLink>https://twitter.com/_Adam_Rodriguez?lang=bg</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">-->
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="no" hasSubtitle='yes' gendre='comedy' produced-by='s19' type='movie'>
            <filmName>Такси </filmName>
            <duration>86</duration>
            <country>Франция</country>
            <year>1998</year>
            <plot>
              Даниел е бивш шофьор, доставчик на пици. Той кара бърза кола, защото
              обича високите скорости. Даниел се сприятелява с полицая Емилиен.
              В Марсилия нахлуват немски престъпници. Даниел помага на Емилиен да ги хванат.
            </plot>
            <audioLanguage>френски език</audioLanguage>
            <rating>7</rating>
            <actorsIN>
                <actor-ref actorID='a30'/>              
            </actorsIN>
       </video>
      
    
   <video isHd='no' hasSubtitle='yes' gendre='comedy' produced-by='s20' type='movie'>
            <filmName>Фанфан Лалето</filmName>
            <duration>97</duration>
            <country>Франция</country>
            <year>2003</year>
            <plot>
              Лентата описва романтичната история на търсач на приключения от времето на Луи XV.
              Швейцарско-испанският актьор Венсан Перес приема предизвикателството и се превъплътява
              в емблематичния образ на Фанфан Лалето. Перес се научава виртуозно да се дуелира с шпага,
              майсторски да галопира на кон и сам изпълнява всички каскади във филма.
            </plot>
            <audioLanguage>френски език</audioLanguage>
            <rating>5</rating>
            <actorsIN>
                <actor-ref actorID='a32'/>
            </actorsIN>
       </video>


      <video isHd='no' hasSubtitle='yes' gendre='comedy' produced-by='s43' type='movie'>
        <filmName>Полунощ в Париж</filmName>
        <duration>94</duration>
        <country>САЩ</country>
        <year>2011</year>
        <plot>
          През 2010 Гил Пендър, успешен холивудски сценарист, и годеницата му Инес са на ваканция в Париж,
          придружавани от родителите на младата дама. През това време Гил се опитва неимоверно да завърши
          първия си роман. Но докато той е готов да остави всичко в името на творчеството си, Инес, която
          го смята за безнадежден мечтател, го съветва да се придържа към работата си като сценарист, в
          която вече е пожънал успехи. Между двамата има много различия, които сякаш стават още по-явни
          в Париж.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>5</rating>
        <actorsIN>
          <actor-ref actorID='a31'/>
        </actorsIN>
      </video>
        
    </videos>


  <studios>
    <studio id='s19'>
      <studioName> ARP Sélection</studioName>
      <director>Люк Бесон</director>
      <address>Марсилия, Франция</address>
      <phone>635987</phone>
    </studio>


    <studio id='s20'>
      <studioName>Canal+</studioName>
      <director>Люк Бесон</director>
      <address>Марсилия, Франция</address>
      <phone>635987</phone>
    </studio>

    <studio id='s43'>
      <studioName>Sony Pictures Classics</studioName>
      <director>Уди Алън</director>
      <address>Ню Йорк, САЩ</address>
      <phone>693279</phone>
    </studio>
  </studios>
  
    <actors>
        <actor gender='F' age='54' id='a30'>
            <name>
                <first>Сами</first>
                <last>Насери</last>
            </name>
            <countryActor>Париж, Франция</countryActor>
            <email>Nasseri@gmail.com</email>
            <actorPhone>148952</actorPhone>
            <socialNetworkLink>http://www.imdb.com/name/nm0618651/</socialNetworkLink>
            <nativeLanguage>френски език</nativeLanguage>
        </actor>
        

         <actor gender='M' age='51' id='a32'>
            <name>
                <first>Венсан</first>
                <last>Перез</last>
            </name>
            <countryActor>Лозана, Швейцария</countryActor>
            <email>Perez@gmail.com</email>
            <actorPhone>666453</actorPhone>
            <socialNetworkLink>http://www.imdb.com/name/nm0001641/</socialNetworkLink>
            <nativeLanguage>френски език</nativeLanguage>
        </actor>

      <actor gender='F' age='40' id='a31'>
        <name>
          <first>Марион</first>
          <last>Котияр</last>
        </name>
        <countryActor>Париж, Франция</countryActor>
        <email>Cotillard@gmail.com</email>
        <actorPhone>463152</actorPhone>
        <socialNetworkLink>http://www.imdb.com/name/nm0182839/</socialNetworkLink>
        <nativeLanguage>френски език</nativeLanguage>
      </actor>
    </actors>
</videolibrary>
