=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT videolibrary (nameSite,siteLink,videos,studios,actors)>
<!ELEMENT nameSite (#PCDATA)>
<!ELEMENT siteLink (#PCDATA)>

<!ELEMENT videos (video+)>
<!ELEMENT video (filmName,duration,country,year,plot,audioLanguage,rating,actorsIN)>
<!ELEMENT filmName (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT year (#PCDATA) >
<!ELEMENT plot (#PCDATA) >
<!ELEMENT audioLanguage (#PCDATA) >
<!ELEMENT rating (#PCDATA) >
<!ELEMENT actorsIN (actor-ref)>
<!ELEMENT actor-ref (#PCDATA)>
<!ATTLIST actor-ref
              actorID IDREF #REQUIRED >
<!ATTLIST video 
            isHd (yes|no) #REQUIRED
            hasSubtitle (yes|no) #REQUIRED
            gendre (action|adventure|comedy|romantic|drama) #REQUIRED
            produced-by IDREF #REQUIRED
            type (movie|tvShow) #REQUIRED>

<!ELEMENT studios (studio+)>
<!ELEMENT studio (studioName,director,address,phone)>
<!ATTLIST studio
              id ID #REQUIRED >
<!ELEMENT studioName (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA) >
<!ELEMENT actors (actor+)>
<!ELEMENT actor (name,countryActor,email,actorPhone,socialNetworkLink,nativeLanguage)>
<!ATTLIST actor
              gender (M|F) #REQUIRED
              age NMTOKEN #REQUIRED
              id ID #REQUIRED>
<!ELEMENT name (first,last)>
<!ELEMENT first (#PCDATA) >
<!ELEMENT  last (#PCDATA) >
<!ELEMENT countryActor (#PCDATA) >
<!ELEMENT  email (#PCDATA) >
<!ELEMENT  actorPhone (#PCDATA) >
<!ELEMENT  socialNetworkLink (#PCDATA) >
<!ELEMENT  nativeLanguage (#PCDATA) >

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="yes" hasSubtitle='yes' gendre='adventure' produced-by='s10' type='movie'>
            <filmName>Карибски пирати: Проклятието на Черната перла</filmName>
            <duration>143</duration>
            <country>САЩ</country>
            <year>2003</year>
            <plot>Уил Търнър е млад ковач, влюбен в Елизабет Суон, дъщеря на губернатора. Една нощ градът е 
                нападнат от пиратския кораб „Черната перла“, чийто екипаж, предвождан от капитана Хектор Барбоса,
                е прокълнат заради алчността си да са нито живи, нито мъртви. Наглед те са обикновени хора, но не
                могат да бъдат убити, и не изпитват удоволствията от живота, а лунната светлина разкрива истинската
                им същност – живи скелети. За да развалят проклятието, им е нужна кръв от някогашния член на екипажа
                Бил „Каиша“ Търнър, а тъй като той вече не е жив – от някой, в когото тече кръвта му. Елизабет се
                представя пред тях с името Елизабет Търнър, и те я вземат по погрешка за дъщеря на Бил Търнър, и я отвличат.
                Уил Търнър решава да я спаси, но не получава подкрепа от другите. Единствената му надежда е хвърленият 
                в тъмница Джак Спароу. Уил го измъква срещу обещание да окаже помощ в освобождаването на Елизабет.
                Хитрият и изобретателен Джак обаче има и своя цел – да си върне „Черната перла“, на която е бил капитан,
                преди Барбоса да организира бунт срещу него
            </plot>
          <audioLanguage>английски език</audioLanguage>
          <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a11'/>
            </actorsIN>
        </video>
        
        
        <video isHd='yes' hasSubtitle='yes' gendre='adventure' produced-by='s11' type='movie'>
            <filmName>Властелинът на пръстените: Задругата на пръстена</filmName>
            <duration>178</duration>
            <country>Нова Зеландия</country>
            <year>2001</year>
            <plot>Младият хобит Фродо и смелата задруга от приятели и съюзници се впускат в опасна мисия, за да 
                унищожат легендарния Единствен пръстен. По петите им са слугите на злия Саурон, Господарят на
                мрака и създател на Пръстена. Ако Саурон си върне Пръстена, Средната земя е обречена. Тази епична
                история за доброто, злото, приятелството и саможертвата, носител на четири награди Оскар, ще ви
                пренесе в свят, който надминава и най-смелите ви фантазии.
            </plot>
          <audioLanguage>английски език</audioLanguage>
          <rating>9</rating>
            <actorsIN>
                <actor-ref actorID='a12'/>
                
            </actorsIN>
        </video>


      <video isHd='no' hasSubtitle='yes' gendre='romantic' produced-by='s35' type='movie'>
        <filmName>Блясъкът на чистия ум</filmName>
        <duration>108</duration>
        <country>САЩ</country>
        <year>2004</year>
        <plot>
          Джоел (Джим Кери) е изумен да научи, че от главата на приятелката му Клемънтайн (Кейт Уинслет)
          е изтрита бурната им връзка. В отчаянието си той се свърза със създателя на процеса д-р Хоуърд
          Майерцвайк (Том Уилкинсън), за да се подложи на същото лечение. Но когато спомените за
          Клемънтайн започват да избледняват, Джоел внезапно осъзнава колко много я обича.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>4</rating>
        <actorsIN>
          <actor-ref actorID='a13'/>
        </actorsIN>
      </video>
      
    </videos>


  <studios>
    <studio id='s10'>
      <studioName>Disney</studioName>
      <director>Гор Вербински</director>
      <address>САЩ</address>
      <phone>555441</phone>
    </studio>

    <studio id='s11'>
      <studioName>Warner Bros. Pictures </studioName>
      <director>Питър Джаксън</director>
      <address>Уелингтън, Нова Зеландия</address>
      <phone>6544044</phone>
    </studio>

    <studio id='s35'>
      <studioName>Focus Features</studioName>
      <director>Мишел Гондри</director>
      <address>Версай, Франция</address>
      <phone>459030</phone>
    </studio>

  </studios>
    
    <actors>
        <actor gender='M' age='52' id='a11'>
            <name>
                <first>Джони</first>
                <last>Деп</last>
            </name>
            <countryActor>Кентъки,САЩ</countryActor>
            <email>Depp@gmail.com</email>
          <actorPhone>124531</actorPhone>
          <socialNetworkLink>https://twitter.com/realdepp?lang=bg</socialNetworkLink>
          <nativeLanguage>английски език</nativeLanguage>
        </actor>
        
        
        <actor gender='M' age='38' id='a12'>
            <name>
                <first>Орландо</first>
                <last>Блум</last>
            </name>
            <countryActor>Кентърбъри, Великобритания</countryActor>
            <email>Bloom@gmail.com</email>
          <actorPhone>215531</actorPhone>
          <socialNetworkLink>https://twitter.com/orlandobloom?lang=bg</socialNetworkLink>
          <nativeLanguage>английски език</nativeLanguage>
        </actor>

      <actor gender='M' age='34' id='a13'>
        <name>
          <first>Илайджа</first>
          <last>Ууд</last>
        </name>
        <countryActor>Айова, САЩ</countryActor>
        <email>Wood@gmail.com</email>
        <actorPhone>422531</actorPhone>
        <socialNetworkLink>https://twitter.com/elijahwood?lang=bg</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>
       
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="yes" hasSubtitle='yes' gendre='action' produced-by='s25' type='movie'>
            <filmName>Зрителна измама</filmName>
            <duration>124</duration>
            <country>Франция</country>
            <year>2013</year>
            <plot>
              Сюжетът на Зрителна измама се фокусира върху опитите агентите от Федералното бюро за разследване
              да арестуват членовете на международната магьосническа трупа Four Horsemen, които за кратък 
              период от време извършват няколко виртуозни банкови обири в Калифорния. 
              Това, което затруднява разследването на ФБР е, че илюзионистите успяват да извършат дръзките си
              обири докато текат представленията им пред нищо неподозираща публика. За да постигне желаните
              резултати, разследващия екип на ФБР привлича пенсиониран илюзионист, който е наясно с всички
              тайни на престъпниците от Four Horsemen.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>6</rating>
            <actorsIN>
                <actor-ref actorID='a43'/>  
            </actorsIN>
       </video>


      <video isHd="no" hasSubtitle='yes' gendre='action' produced-by='s49' type='movie'>
        <filmName>Белите не могат да скачат</filmName>
        <duration>115</duration>
        <country>САЩ</country>
        <year>1992</year>
        <plot>
          Това е една комедия за двама баскетболни маниаци – чернокож и бял. На игрището
          Били и Сидни разбиват представата, че белите не могат да играят баскетбол толкова
          добре колкото черните. Всичко е прекрасно, но има няколко малки подробности, които
          усложняват нещата... Били е задлъжнял с голяма сума пари и е преследван от гангстери,
          а и двамата със Сидни си имат своите разногласия...
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>3</rating>
        <actorsIN>
          <actor-ref actorID='a44'/>
        </actorsIN>
      </video>


      <video isHd="no" hasSubtitle='yes' gendre='adventure' produced-by='s50' type='movie'>
        <filmName>Отмъстителите</filmName>
        <duration>143</duration>
        <country>САЩ</country>
        <year>2012</year>
        <plot>
          „Отмъстителите“ (на английски: The Avengers) е американски супергеройски филм от 2012 г.,
          включващ героите на Железния човек, Хълк, Тор, Капитан Америка, Ястребово око и Черната
          вдовица, и е шести подред филм в Киновселената на Марвел. Филмът си има три продължения
          - Отмъстителите: Ерата на Ултрон от 2015 г., Отмъстителите: Войни на безкрайността - 
          1-ва част от 2018 г. и Отмъстителите: Войни на безкрайността - 2-ра част от 2019 г.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>4</rating>
        <actorsIN>
          <actor-ref actorID='a45'/>
        </actorsIN>
      </video>
    </videos>


  <studios>
    <studio id='s25'>
      <studioName>Summit Entertainment</studioName>
      <director>Луи Летерие</director>
      <address>САЩ</address>
      <phone>4569</phone>
    </studio>

    <studio id='s49'>
      <studioName>20th Century Fox</studioName>
      <director>Рон Шелтън</director>
      <address>САЩ</address>
      <phone>7412</phone>
    </studio>

    <studio id='s50'>
      <studioName>Paramount Pictures</studioName>
      <director>Джос Уидън</director>
      <address>Ню Йорк, САЩ</address>
      <phone>7893</phone>
    </studio>
  </studios>
  
    <actors>
        <actor gender='F' age='40' id='a43'>
            <name>
                <first>Айла</first>
                <last>Фишър</last>
            </name>
            <countryActor>Маскат, Оман</countryActor>
            <email>Fisher@gmail.com</email>
            <actorPhone>636363</actorPhone>
            <socialNetworkLink>https://twitter.com/IslaKFisher</socialNetworkLink>
            <nativeLanguage>английски език</nativeLanguage>
        </actor>


      <actor gender='M' age='54' id='a44'>
        <name>
          <first>Уди</first>
          <last>Харелсън</last>
        </name>
        <countryActor>Тексас, САЩ</countryActor>
        <email>harrelson@gmail.com</email>
        <actorPhone>796541</actorPhone>
        <socialNetworkLink>https://twitter.com/ImWoodyHarelson</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>

      <actor gender='M' age='48' id='a45'>
        <name>
          <first>Марк</first>
          <last>Ръфало</last>
        </name>
        <countryActor>Уисконсин, САЩ</countryActor>
        <email>Ruffalo@gmail.com</email>
        <actorPhone>789865</actorPhone>
        <socialNetworkLink>https://twitter.com/MarkRuffalo</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="yes" hasSubtitle='yes' gendre='adventure' produced-by='s21' type='movie'>
            <filmName>Хари Потър</filmName>
            <duration>86</duration>
            <country>Великобритания</country>
            <year>2001</year>
            <plot>
              Хари Потър е осиротяло момче, отгледано от леля си и вуйчо си. На 11 години,
              полу-великана Рубиъс Хагрид го информира, че всъщност е магьосник, а 
              родителите му са били убити от злия магьосник Лорд Волдемор. Същата нощ Волдемор
              се е опитал да убие и малкия Хари, но проклятието му се върнало към него и го 
              превърнало в слаба и безпомощна форма. В резултат на това Хари става изключително
              известен в магьосническия свят. Хари започва първата си година в училището за магия
              и вълшебство Хогуортс и се учи за магията.
            </plot>
            <audioLanguage>английски език</audioLanguage>
            <rating>10</rating>
            <actorsIN>
                <actor-ref actorID='a34'/>   
            </actorsIN>
       </video>


      <video isHd="yes" hasSubtitle='yes' gendre='adventure' produced-by='s45' type='movie'>
        <filmName>Ной </filmName>
        <duration>138</duration>
        <country>САЩ</country>
        <year>2014</year>
        <plot>
          „Ной“ е американски филм от 2014 г. на режисьора Дарън Аронофски, базиран
          на историята за Потопа и Ноевия ковчег от „Битие“.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>7</rating>
        <actorsIN>
          <actor-ref actorID='a35'/>
        </actorsIN>
      </video>


      <video isHd="no" hasSubtitle='yes' gendre='action' produced-by='s46' type='movie'>
        <filmName>Дива мишена </filmName>
        <duration>98</duration>
        <country>Великобритания</country>
        <year>2010</year>
        <plot>
          Виктор Мейнарт (Бил Найт) е професионален убиец. Той следва семейния бизнес, като
          убива мишените си. Фъргюсън (Рупърт Еверет) наема Виктор Мейнарт, за да убие Роуз 
          (Емили Блънт). Тя трябва да умре, защото е измамамила Фъргюсън, като му е продала
          една от „най-скъпите картини в света“. Тя познава реставратора в галерията, у когото
          е истинската картина. Той успява да изкопира картината. По този начин Роуз продава 
          картината за 900 000 паунда. След като Мейнарт успява да се прицели в мишената, се
          отказва, защото се влюбва в нея. След това Фъргюсън наема Диксън, за да свърши 
          работата му.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>5</rating>
        <actorsIN>
          <actor-ref actorID='a36'/>
        </actorsIN>
      </video>
    </videos>


  <studios>
    <studio id='s21'>
      <studioName>Warner Bros. Pictures</studioName>
      <director>Дейвид Хеймън</director>
      <address>Великобритания</address>
      <phone>2456</phone>
    </studio>

    <studio id='s45'>
      <studioName>Paramount Pictures</studioName>
      <director>Дарън Аронофски</director>
      <address>САЩ</address>
      <phone>1112</phone>
    </studio>

    <studio id='s46'>
      <studioName> Magic Light Pictures</studioName>
      <director>Джонатан Лин</director>
      <address>Великобритания</address>
      <phone>1113</phone>
    </studio>
  </studios>
  
    <actors>
        <actor gender='F' age='26' id='a35'>
            <name>
                <first>Ема</first>
                <last>Уотсън</last>
            </name>
            <countryActor>Париж, Франция</countryActor>
            <email>Watson@gmail.com</email>
            <actorPhone>124563</actorPhone>
            <socialNetworkLink>https://twitter.com/emmawatsonvip</socialNetworkLink>
            <nativeLanguage>английски език</nativeLanguage>
        </actor>

      <actor gender='M' age='26' id='a34'>
        <name>
          <first>Даниъл</first>
          <last>Радклиф</last>
        </name>
        <countryActor>Лондон, Англия</countryActor>
        <email>Radcliff@gmail.com</email>
        <actorPhone>635433</actorPhone>
        <socialNetworkLink>https://twitter.com/DanJRadcliffeNL</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>

      <actor gender='M' age='27' id='a36'>
        <name>
          <first>Рупърт</first>
          <last>Гринт</last>
        </name>
        <countryActor>Хартфордшър, Великобритания</countryActor>
        <email>Grintt@gmail.com</email>
        <actorPhone>999632</actorPhone>
        <socialNetworkLink>https://twitter.com/MoreRupertGrint</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>
    </actors>
</videolibrary>

=== AneliaBlagoeva/MovieCatalog/App_Data/videolibrary11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">-->
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video isHd="no" hasSubtitle='no' gendre='comedy' produced-by='s18' type='movie'>
            <filmName>Живи легенди</filmName>
            <duration>96</duration>
            <country>България</country>
            <year>2009</year>
            <plot>Павел е тридесет и няколко годишен мъж, работещ на висок пост в елитна банка. Един ден
            претърпява инцидент и изпада в кома. Когато се събужда се оказва, че има частична амнезия и
            не си спомня нищо след абитуриентския си бал.Той решава да се върне в родния си град, за да
            ги открие.Пристигайки там установява, че те отдавна са поели в различни посоки, прекъснали
            са връзката помежду си и за най-голямо негово учудване са направили редица компромиси със себе си.
            С детския си начин на мислене Павел решава да ги върне към тийнейджърските им години като
            ги забърква в поредица от щуротии, които преобръщат живота им по неочакван дори и за него начин.
            </plot>
            <audioLanguage>български език</audioLanguage>
            <rating>5</rating>
            <actorsIN>
                <actor-ref actorID='a28'/>       
            </actorsIN>
       </video>
      
    
   <video hasSubtitle='no' gendre='comedy' produced-by='s18' type='movie'>
            <filmName>Чужденецът</filmName>
            <duration>100</duration>
            <country>България</country>
            <year>2012</year>
            <plot>Павел е тридесет и няколко годишен мъж, работещ на висок пост в елитна банка. Един ден
            претърпява инцидент и изпада в кома. Когато се събужда се оказва, че има частична амнезия и
            не си спомня нищо след абитуриентския си бал.Той решава да се върне в родния си град, за да
            ги открие.Пристигайки там установява, че те отдавна са поели в различни посоки, прекъснали
            са връзката помежду си и за най-голямо негово учудване са направили редица компромиси със себе си.
            С детския си начин на мислене Павел решава да ги върне към тийнейджърските им години като
            ги забърква в поредица от щуротии, които преобръщат живота им по неочакван дори и за него начин.
            </plot>
            <audioLanguage>български език</audioLanguage>
            <rating>5</rating>
            <actorsIN>
                <actor-ref actorID='a27'/>
            </actorsIN>
       </video>


      <video isHd='yes' hasSubtitle='yes' gendre='adventure' produced-by='s55' type='movie'>
        <filmName>Интерстелар</filmName>
        <duration>169</duration>
        <country>САЩ</country>
        <year>2014</year>
        <plot>
          Действието на филма се развива в едно близко бъдеще, в което светът агонизира от липсата на хранителни
          запаси, а климатът на Земята рязко се влошава, предизвиквайки глобална суша, облаци от прах и гигантски
          пясъчни бури. Тук се появява и историята на бившия пилот Купър (Матю Макконъхи), който работи по програма
          за фермери и отглежда царевица. Тя е единственото растение, което не е покосено от „чумата“ на главнята.
          Освен за царевицата, Купър се грижи сам за двете си деца. Стечение на обстоятелствата отвеждат Купър в
          секретен научен център, изучаващ новопоявила се „червеева дупка“ в близост до Сатурн. Целта на екипа,
          представляващ останки от бившата космическа агенция НАСА и предвождан от професор Бранд (Майкъл Кейн)
          е да се изпрати кораб в дупката и така да се изследва една далечна галактика, в която да търси нов
          дом за човешката раса.
        </plot>
        <audioLanguage>английски език</audioLanguage>
        <rating>8</rating>
        <actorsIN>
          <actor-ref actorID='a55'/>
        </actorsIN>
      </video>
      
    </videos>


  <studios>
    <studio id='s18'>
      <studioName>BTV Studios</studioName>
      <director>Ники Илиев</director>
      <address>София, България</address>
      <phone>141516</phone>
    </studio>


    <studio id='s55'>
      <studioName>Paramount Pictures</studioName>
      <director>Кристофър Нолан</director>
      <address>Лондон, Великобритания</address>
      <phone>3212</phone>
    </studio>
  </studios>
  
    <actors>

      <actor gender='M' age='46' id='a55'>
        <name>
          <first>Матю</first>
          <last>Макконъхи</last>
        </name>
        <countryActor>Тексас, САЩ</countryActor>
        <email>McConaughey@gmail.com</email>
        <actorPhone>456531</actorPhone>
        <socialNetworkLink>http://www.imdb.com/name/nm0000190/?ref_=tt_cl_t2</socialNetworkLink>
        <nativeLanguage>английски език</nativeLanguage>
      </actor>
      
        <actor gender='F' age='33' id='a27'>
            <name>
                <first>Саня</first>
                <last>Борисова</last>
            </name>
            <countryActor>Видин, България</countryActor>
            <email>SaniaBorisova@gmail.com</email>
            <actorPhone>777777</actorPhone>
            <socialNetworkLink>https://www.facebook.com/SanyaBorisovaIlieva/</socialNetworkLink>
            <nativeLanguage>български език</nativeLanguage>
        </actor>
        
        
        <actor gender='F' age='37' id='a28'>
            <name>
                <first>Яна</first>
                <last>Маринова</last>
            </name>
            <countryActor>София,България</countryActor>
            <email>IanaMarinova@gmail.com</email>
            <actorPhone>789321</actorPhone>
            <socialNetworkLink>https://www.facebook.com/Yana-Marinova-%D0%AF%D0%BD%D0%B0-%D0%9C%D0%B0%D1%80%D0%B8%D0%BD%D0%BE%D0%B2%D0%B0-284148661602759/</socialNetworkLink>
            <nativeLanguage>български език</nativeLanguage>
        </actor>

    </actors>
</videolibrary>
